# Generated by Django 4.1.5 on 2023-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridertravelinfo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=10),
        ),
    ]
