# Generated by Django 4.1.5 on 2023-01-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_ridertravelinfo_status_transportrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridertravelinfo',
            old_name='to',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='ridertravelinfo',
            old_name='_from',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='transportrequest',
            old_name='to',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='transportrequest',
            old_name='_from',
            new_name='source',
        ),
    ]
