# Generated by Django 4.1.5 on 2023-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_ridertravelinfo_status_matchedassets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedassets',
            name='applied',
        ),
        migrations.AlterField(
            model_name='ridertravelinfo',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'APPLIED'), ('NOT_APPLIED', 'NOT_APPLIED')], default='NOT_APPLIED', max_length=20),
        ),
    ]
